// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "eu-west-1",
    "aws_dynamodb_all_tables_region": "eu-west-1",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "users",
            "region": "eu-west-1"
        },
        {
            "tableName": "projects",
            "region": "eu-west-1"
        }
    ],
    "aws_cognito_identity_pool_id": "eu-west-1:f308e931-8695-4bad-9461-85713632b61d",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_uQ9bz9JkO",
    "aws_user_pools_web_client_id": "2btnbmuebdc0vr6nasuhi0c49v",
    "aws_cloud_logic_custom": [
        {
            "name": "usersCRUD",
            "endpoint": "https://ugt1tfxsii.execute-api.eu-west-1.amazonaws.com/Prod",
            "region": "eu-west-1"
        },
        {
            "name": "projectsCRUD",
            "endpoint": "https://eiymxefuj6.execute-api.eu-west-1.amazonaws.com/Prod",
            "region": "eu-west-1"
        },
        {
            "name": "email",
            "endpoint": "https://obz564xhuf.execute-api.eu-west-1.amazonaws.com/Prod",
            "region": "eu-west-1"
        }
    ],
    "aws_content_delivery_bucket": "myapp-20181110200130--hostingbucket",
    "aws_content_delivery_bucket_region": "eu-west-1",
    "aws_content_delivery_url": "http://myapp-20181110200130--hostingbucket.s3-website-eu-west-1.amazonaws.com"
};


export default awsmobile;
