// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "eu-west-1",
    "aws_content_delivery_bucket": "myapp-20181024193007--hostingbucket",
    "aws_content_delivery_bucket_region": "eu-west-1",
    "aws_content_delivery_url": "http://myapp-20181024193007--hostingbucket.s3-website-eu-west-1.amazonaws.com",
    "aws_cognito_identity_pool_id": "eu-west-1:5575f27c-ba61-4f62-9e35-5fcb82bf9891",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_6tMR9zkZI",
    "aws_user_pools_web_client_id": "7enm37u5mn47u7er90r7hlhio8"
};


export default awsmobile;
